### ISSUE TITLE
No Debug.xcconfig

### ISSUE THREAD

**Issue by BryanJBryce** [fishjam-dev/ios-client-sdk#12]
Readme says:

> Developing
> 
> Run ./scripts/init.sh in the main directory to install swift-format and release-it and set up git hooks
> Edit Debug.xcconfig to set backend url in development.
> Run release-it to release. Follow the prompts, it should update version in podspec, make a commit and tag and push the new version.

There is no `Debug.xcconfig` committed to the repo

**Comment by incubo4u** [comment]
run ./scripts/init.sh in the main directory
